language: c

sudo: false

addons:
  postgresql: "9.3"

services:
  - mysql

env:
  global:
    - LUAROCKS=2.2.2
    - OPENRESTY=1.9.3.2
  matrix:
    - LUA=luajit2.1

before_install:
  - source install_openresty.sh
  - source .travis/setenv_lua.sh

install:
  - luarocks install https://luarocks.org/manifests/olivine-labs/busted-2.0.rc11-0.rockspec
  - luarocks install moonscript
  - luarocks install luaposix
  - luarocks install date
  - luarocks install luasql-mysql MYSQL_INCDIR=/usr/include/mysql
  - luarocks make

before_script:
  - createdb -U postgres lapis_test
  - mysql -e 'create database lapis_test;'

script: 
  - busted
  - busted spec_postgres/
  - busted spec_mysql/


